name: KICS Code analysis

on: 
  workflow_call
    inputs:
      ENABLE_COMMENTS
        required: true 
        type: boolean
      WORKING_DIRECTORY:
        REQUIRED: true 
        type: string

jobs:
  kics:
    - name: Run KICS Code Analysis
    if: github.event_name == 'pull_request'
    run-0n: ubuntu-24.04
    steps:
    - name: checkout
     uses: actions/checkout@v3 
     with:
       ref: ${{github.event.pull_request.head.ref}}

    - name: Run KICS scan
      uses: checkmarx/kics-github-action@v2.0.0
      with: 
       path: ${{ input.WORKING_DIRECTORY }}
       token: ${{ secret.GITHUB_TOKEN }}
       output_path: myresult/
       ignore_on_exit: results
       enable_comments: ${{ inputs.ENABLE_COMMENTS }} 

    - name: Display KICS results
      run:
        cat myResults/result.json


  