# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "cloudsentrics-batch5-devsecops"
    dynamodb_table = "cloudsentrics-terraform-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
