# Run on call from another workflow

on:
  workflow_call:
    inputs:
      TERRAFORM_VERSION:
        description: "Terraform version to be installed on the runner"
        required: true
        type: string

      TERRAGRUNT_VERSION:
        description: "Terragrunt version to be installed on the runner"
        required: true
        type: string  

      TERRAFORM_WORKING_DIR:
        description: "Path to the Terraform configuration"
        required: true
        type: string

      AWS_REGION:
        description: "AWS region to be used"
        required: true
        type: string

      ENVIRONMENT_NAME:
        description: "Name of the environment"
        required: true
        type: string

jobs:
  apply:
    name: "Terragrunt Apply"
    environment: ${{ inputs.ENVIRONMENT_NAME }}
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04  # Corrected from 'ubuntu-24.04' to 'ubuntu-20.04'
    defaults:
      run:
        working-directory: ${{ inputs.TERRAFORM_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3  # Corrected from 'v3' to 'v1'
        with:
          terraform_version: ${{ inputs.TERRAFORM_VERSION }}
          terraform_wrapper: true

      - name: Install Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt_version: ${{ inputs.TERRAGRUNT_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Terragrunt Init
        id: init
        run: terragrunt run-all init -no-color --terragrunt-non-interactive

      - name: Terragrunt Apply
        id: apply
        run: terragrunt run-all apply -no-color --terragrunt-non-interactive
        continue-on-error: true



        